### ISSUE TITLE
Keeps running on Windows with path C:\

### ISSUE THREAD

**Issue by dietergeerts** [maxrimue/parent-package-json#26]
There should be a check that works on Windows. I now use https://www.npmjs.com/package/parent-package instead, though I find this usage nicer.

**Comment by maxrimue** [comment]
Thanks for reporting and sorry for not replying sooner. Could you elaborate? Do you mean that this module gets "stuck" in the root directory on Windows when going up paths?

**Comment by maxrimue** [comment]
Closed as #27 seems to have done the trick
